apiVersion: v1
kind: Pod
metadata:
  name: test-manila
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: mypvc
        mountPath: /moon
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: manila-netapp
