kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manila-netapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-manila-netapp
